"""Add experience_years to Worker

Revision ID: 1e3ec8eb8c09
Revises: 5021e7a76071
Create Date: 2025-07-07 17:03:44.822746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3ec8eb8c09'
down_revision: Union[str, None] = '5021e7a76071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('experience_years', sa.Integer(), nullable=True))
    op.add_column('workers', sa.Column('certificate_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'certificate_url')
    op.drop_column('workers', 'experience_years')
    # ### end Alembic commands ###
