"""Added is_verified, cert_url, portfolio media fields

Revision ID: 27cf939c9f2a
Revises: 6a116667fbdc
Create Date: 2025-06-22 12:19:32.589500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27cf939c9f2a'
down_revision = '6a116667fbdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
