""" Tweaks here and there

Revision ID: 3abcaea1c029
Revises: 1e3ec8eb8c09
Create Date: 2025-07-07 18:13:35.350565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3abcaea1c029'
down_revision: Union[str, None] = '1e3ec8eb8c09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill', 'is_active')
    # ### end Alembic commands ###
