"""Gender to sign up

Revision ID: 5021e7a76071
Revises: 2461b5472b3d
Create Date: 2025-07-07 16:27:31.952962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5021e7a76071'
down_revision: Union[str, None] = '2461b5472b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('gender', sa.String(length=10), nullable=False, server_default='female'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'gender')
    # ### end Alembic commands ###
