"""Updated Skill model or added skills logic

Revision ID: 5fb93d349ae1
Revises: 1cbf45c745d3
Create Date: 2025-06-24 18:26:16.391736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5fb93d349ae1'
down_revision = '1cbf45c745d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certifications')
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_column('location')

    op.create_table('certifications',
    sa.Column('certification_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('certification_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('issued_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('issue_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('expiration_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='certificationstatus'), autoincrement=False, nullable=True),
    sa.Column('verified_by_admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['verified_by_admin_id'], ['admins.admin_id'], name=op.f('certifications_verified_by_admin_id_fkey')),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], name=op.f('certifications_worker_id_fkey')),
    sa.PrimaryKeyConstraint('certification_id', name=op.f('certifications_pkey'))
    )
    # ### end Alembic commands ###
