"""Changes to models

Revision ID: 6a116667fbdc
Revises: adc2cb11426d
Create Date: 2025-06-19 09:16:12.677649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a116667fbdc'
down_revision = 'adc2cb11426d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('OPEN', 'REQUESTED', 'IN_PROGRESS', 'COMPLETED', name='jobstatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('OPEN', 'REQUESTED', 'IN_PROGRESS', 'COMPLETED', name='jobstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
