"""edit to skill name

Revision ID: 86fee07c3ed7
Revises: dcfc70ab15a9
Create Date: 2025-07-04 06:47:34.672168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86fee07c3ed7'
down_revision: Union[str, None] = 'dcfc70ab15a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('skill_name', sa.String(length=100), nullable=True))
    op.execute("""
        UPDATE jobs 
        SET skill_name = s.skill_name
        FROM skill s 
        WHERE jobs.skill_id = s.skill_id
    """)
    op.alter_column('jobs', 'skill_name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workers', 'id_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('jobs', 'skill_name')
    # ### end Alembic commands ###
