"""Add address fields to jobs

Revision ID: 9ab89bf82307
Revises: bc19f75709ef
Create Date: 2025-07-07 15:42:13.826516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab89bf82307'
down_revision: Union[str, None] = 'bc19f75709ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('road', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('building_name', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('house_number', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'house_number')
    op.drop_column('jobs', 'building_name')
    op.drop_column('jobs', 'road')
    # ### end Alembic commands ###
