"""remove full name from admin

Revision ID: b2453360bd9a
Revises: f1feb18d9c01
Create Date: 2025-07-06 03:52:35.099311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2453360bd9a'
down_revision: Union[str, None] = 'f1feb18d9c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'fullname')
    op.drop_column('skill', 'category')
    op.alter_column('workers', 'id_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workers', 'id_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('skill', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('admins', sa.Column('fullname', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
