"""Add assigned_at and completed_at to Job

Revision ID: bc19f75709ef
Revises: af6b82840245
Create Date: 2025-07-07 09:38:40.102498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc19f75709ef'
down_revision: Union[str, None] = 'af6b82840245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('assigned_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'completed_at')
    op.drop_column('jobs', 'assigned_at')
    # ### end Alembic commands ###
