"""initial migration

Revision ID: c072c05e4de4
Revises: 
Create Date: 2025-07-08 05:15:08.971044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c072c05e4de4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clients',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('skill',
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('skill_id')
    )
    op.create_table('workers',
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('id_number', sa.String(length=50), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('requests', 'approved', 'rejected', name='workerstatus'), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('certificate_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_table('jobs',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('road', sa.String(length=255), nullable=True),
    sa.Column('building_name', sa.String(length=255), nullable=True),
    sa.Column('house_number', sa.String(length=100), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('scheduled_time', sa.Time(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'REQUESTED', 'IN_PROGRESS', 'WORKER_COMPLETED', 'COMPLETED', name='jobstatus'), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('worker_completion_confirmed', sa.Boolean(), nullable=True),
    sa.Column('client_completion_confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.skill_id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('worker_portfolio',
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ),
    sa.PrimaryKeyConstraint('portfolio_id')
    )
    op.create_table('worker_skills',
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.skill_id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ),
    sa.PrimaryKeyConstraint('worker_id', 'skill_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.String(length=50), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('receiver_type', sa.String(length=50), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('ratings',
    sa.Column('rating_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('rater_id', sa.Integer(), nullable=False),
    sa.Column('rater_type', sa.String(length=50), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('receiver_type', sa.String(length=50), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rating_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    op.drop_table('messages')
    op.drop_table('worker_skills')
    op.drop_table('worker_portfolio')
    op.drop_table('jobs')
    op.drop_table('workers')
    op.drop_table('skill')
    op.drop_table('clients')
    op.drop_table('admins')
    # ### end Alembic commands ###
