"""Add deactivated_by to Client

Revision ID: c922c5445780
Revises: 664ccb4e5e00
Create Date: 2025-07-10 05:48:40.367383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c922c5445780'
down_revision = '664ccb4e5e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('deactivated_by', sa.String(), nullable=True))

    #with op.batch_alter_table('clients', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('deactivated_by', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'deactivated_by')
    #with op.batch_alter_table('clients', schema=None) as batch_op:
        #batch_op.drop_column('deactivated_by')

    # ### end Alembic commands ###
