"""adding job id to ratings

Revision ID: f1feb18d9c01
Revises: 86fee07c3ed7
Create Date: 2025-07-04 09:02:32.629812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1feb18d9c01'
down_revision: Union[str, None] = '86fee07c3ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ratings_job_id_fkey'), 'ratings', type_='foreignkey')
    op.create_foreign_key(None, 'ratings', 'jobs', ['job_id'], ['job_id'], ondelete='CASCADE')
    op.alter_column('workers', 'id_number',
        existing_type=sa.VARCHAR(length=50),
        nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workers', 'id_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.create_foreign_key(op.f('ratings_job_id_fkey'), 'ratings', 'jobs', ['job_id'], ['job_id'])
    # ### end Alembic commands ###
